"#definition of the input variables\n"
"##inputvar: #name of the variable as declared in the code\n"
"## COMMENT: This is the description of the variable as will appear in the logfile\n"
"## RANGE: [from,to] #always put two numbers (also .inf) can be put\n"
"## EXCLUSIVE: #here follows a list of allowed values (either RANGE or EXCLUSIVE)\n"
"##  - Value1:  comments of value1\n"
"##  - Value2:  comment of value2\n"
"## CONDITION: #here the conditions for which the variable makes sense are written\n"
"##   MASTER_KEY: foo #this means that inputvar makes sense only if foo is specified\n"
"##   WHEN: #provide a list of allowed values of foo for which inputvars is meaningful\n"
"##     - fooval1\n"
"##     - fooval2   \n"
"## PROFILE_FROM: foo #inputvar inherit the profile from the one specified by foo variable\n"
"###then the profiles follows, which gives to the variables the allowed name\n"
"## default: value of the default, written as a string \n"
"## profile1: value1 # if the user specifies inputvar: profile1 then inputvars will be value1\n"
"## profile2: value2\n"
"############################################ \n"
" dft:\n"
"   hgrids:\n"
"     COMMENT: grid spacing in the three directions (bohr)\n"
"     RANGE: [0., 2.]\n"
"     default: [0.45, 0.45, 0.45]\n"
"     fast: [0.55, 0.55, 0.55]\n"
"     accurate: [0.30, 0.30, 0.30]\n"
"   rmult:\n"
"     COMMENT: c(f)rmult*radii_cf(:,1(2))=coarse(fine) atom-based radius\n"
"     RANGE: [0., 100.]\n"
"     default: [5., 8.]\n"
"   ixc:\n"
"     COMMENT: exchange-correlation parameter (LDA=1,PBE=11)\n"
"     default: 1\n"
"     PBE: 11\n"
"     Hybrid: -406\n"
"   ncharge:\n"
"     COMMENT: charge of the system\n"
"     RANGE: [-500., 500.]\n"
"     default: 0\n"
"   elecfield:\n"
"     COMMENT: electric field (Ex,Ey,Ez)\n"
"     default: [0., 0., 0.]\n"
"   nspin:\n"
"     COMMENT: spin polarization\n"
"     EXCLUSIVE:\n"
"       1: no spin\n"
"       2: collinear\n"
"       4: non-collinear\n"
"     default: 1\n"
"   mpol:\n"
"     COMMENT: total magnetic moment\n"
"     default: 0\n"
"   gnrm_cv:\n"
"     COMMENT: convergence criterion gradient\n"
"     RANGE: [1.e-20, 1.]\n"
"     default: 1e-4\n"
"     fast: 1e-3\n"
"     accurate: 1e-5\n"
"   itermax:\n"
"     COMMENT: max. # of wfn. opt. steps\n"
"     RANGE: [0, 10000]\n"
"     default: 50\n"
"   nrepmax:\n"
"     COMMENT: max. # of re-diag. runs\n"
"     RANGE: [0, 1000]\n"
"     default: 1\n"
"     accurate: 10\n"
"   ncong:\n"
"     COMMENT: # of CG it. for preconditioning eq.\n"
"     RANGE: [0, 20]\n"
"     default: 6\n"
"   idsx:\n"
"     COMMENT: wfn. diis history\n"
"     RANGE: [0, 15]\n"
"     default: 6\n"
"     low memory: 2\n"
"   dispersion:\n"
"     COMMENT: dispersion correction potential (values 1,2,3,4,5), 0=none\n"
"     RANGE: [0, 5]\n"
"     default: 0\n"
"   inputpsiid:\n"
"     default: 0\n"
"     EXCLUSIVE:\n"
"       -1000: empty\n"
"       -2: random\n"
"       -1: CP2K\n"
"       0: LCAO\n"
"       1: wvl. in mem.\n"
"       2: wvl. on disk\n"
"       10: LCAO + gauss.\n"
"       11: gauss. in mem.\n"
"       12: gauss. on disk\n"
"       100: Linear AO\n"
"       101: Linear restart\n"
"       102: Linear on disk\n"
"   output_wf:\n"
"     default: 0\n"
"     EXCLUSIVE:\n"
"       0: none\n"
"       1: plain text\n"
"       2: Fortran binary\n"
"       3: ETSF file format\n"
"   output_denspot:\n"
"     default: 0\n"
"     EXCLUSIVE:\n"
"       0: none\n"
"       1: density in plain text\n"
"       2: density and potentials in plain text\n"
"       11: density in ETSF file format\n"
"       12: density and potentials in ETSF file format\n"
"       21: density in cube file format\n"
"       22: density and potentials in cube file format\n"
"   rbuf:\n"
"     COMMENT: length of the tail (AU)\n"
"     RANGE: [0., 10.]\n"
"     default: 0.\n"
"     with tails: 5.\n"
"   ncongt:\n"
"     COMMENT: # tail CG iterations\n"
"     RANGE: [0, 50]\n"
"     default: 30\n"
"   norbv:\n"
"     COMMENT: Davidson subspace dim.\n"
"     RANGE: [-9999, 9999]\n"
"     default: 0\n"
"   nvirt:\n"
"     COMMENT: # of opt. orbs\n"
"     RANGE: [0, 9999]\n"
"     default: 0\n"
"   nplot:\n"
"     COMMENT: # of plottec orbs\n"
"     RANGE: [0, 9999]\n"
"     default: 0\n"
"   disablesym:\n"
"     COMMENT: disable the symmetry detection\n"
"     default: No\n"
" kpt:\n"
"   method:\n"
"     COMMENT: K-point sampling method\n"
"     EXCLUSIVE:\n"
"       auto: based on kptrlen\n"
"       MPGrid: Monkhorst-Pack\n"
"       manual: based on raw coordinates\n"
"     default: manual\n"
"   kptrlen:\n"
"     COMMENT: Equivalent length of K-space resolution (Bohr)\n"
"     CONDITION:\n"
"       MASTER_KEY: method\n"
"       WHEN:\n"
"       - auto\n"
"     RANGE: [0, 1e4]\n"
"     default: 0.\n"
"   ngkpt:\n"
"     COMMENT: No. of Monkhorst-Pack grid points\n"
"     CONDITION:\n"
"       MASTER_KEY: method\n"
"       WHEN:\n"
"       - MPGrid\n"
"     RANGE: [1, 10000]\n"
"     default: [1, 1, 1]\n"
"   shiftk:\n"
"     COMMENT: Grid shifts\n"
"     CONDITION:\n"
"       MASTER_KEY: method\n"
"       WHEN:\n"
"       - MPGrid\n"
"     default: [0., 0., 0.]\n"
"   kpt:\n"
"     COMMENT: Kpt coordinates\n"
"     CONDITION:\n"
"       MASTER_KEY: method\n"
"       WHEN:\n"
"       - manual\n"
"     default:\n"
"     -  [0., 0., 0.]\n"
"   wkpt:\n"
"     COMMENT: Kpt weights\n"
"     CONDITION:\n"
"       MASTER_KEY: method\n"
"       WHEN:\n"
"       - manual\n"
"     RANGE: [0., 1e4]\n"
"     default:\n"
"     - 1.\n"
"   bands:\n"
"     COMMENT: For doing band structure calculation\n"
"     default: No\n"
"   iseg:\n"
"     COMMENT: points for each segment of the BZ path\n"
"     CONDITION:\n"
"       MASTER_KEY: bands\n"
"       WHEN:\n"
"       - Yes\n"
"     default:\n"
"     - 1\n"
"   kptv:\n"
"     CONDITION:\n"
"       MASTER_KEY: bands\n"
"       WHEN:\n"
"       - Yes\n"
"     default:\n"
"     -  [0., 0., 0.]\n"
"     -  [0.5, 0.5, 0.5]\n"
"   ngranularity:\n"
"     COMMENT: # of points done for each group\n"
"     CONDITION:\n"
"       MASTER_KEY: bands\n"
"       WHEN:\n"
"       - Yes\n"
"     RANGE: [1, 1000]\n"
"     default: 1\n"
"   band_structure_filename:\n"
"     CONDITION:\n"
"       MASTER_KEY: bands\n"
"       WHEN:\n"
"       - Yes\n"
"     default: ''\n"
" geopt:\n"
"   method:\n"
"     COMMENT: Geometry optimisation method\n"
"     EXCLUSIVE:\n"
"       none: no geometry optimization\n"
"       SDCG: a combination of Steepest Descent and Conjugate Gradient\n"
"       VSSD: Variable Stepsize Steepest Descent method\n"
"       LBFGS: limited-memory BFGS\n"
"       BFGS: Broyden-Fletcher-Goldfarb-Shanno\n"
"       PBFGS: Same as BFGS with an initial Hessian obtained from a force field\n"
"       AB6MD: molecular dynamics from ABINIT\n"
"       DIIS: direct inversion of iterative subspace\n"
"       FIRE: Fast Inertial Relaxation Engine as described by Bitzek et al.\n"
"     default: none\n"
"   ncount_cluster_x:\n"
"     COMMENT: Maximum number of force evaluations\n"
"     RANGE: [0, 2000]\n"
"     PROFILE_FROM: method\n"
"     default: 50\n"
"     none: 1\n"
"   frac_fluct:\n"
"     RANGE: [0., 10.]\n"
"     default: 1.\n"
"   forcemax:\n"
"     RANGE: [0., 10.]\n"
"     default: 0.\n"
"   randdis:\n"
"     COMMENT: random displacement amplitude\n"
"     RANGE: [0., 10.]\n"
"     default: 0.\n"
"   betax:\n"
"     COMMENT: Stepsize for the geometry optimisation\n"
"     CONDITION:\n"
"       MASTER_KEY: method\n"
"       WHEN:\n"
"       - SDCG\n"
"       - VSSD\n"
"       - LBFGS\n"
"       - BFGS\n"
"       - PBFGS\n"
"       - DIIS\n"
"       - FIRE\n"
"       - none\n"
"     PROFILE_FROM: method\n"
"     RANGE: [0., 100.]\n"
"     default: 4.\n"
"     DIIS: 2.\n"
"   history:\n"
"     COMMENT: history for DIIS method\n"
"     CONDITION:\n"
"       MASTER_KEY: method\n"
"       WHEN:\n"
"       - DIIS\n"
"     RANGE: [0, 100]\n"
"     default: 4\n"
"   dtinit:\n"
"     COMMENT: initial time step for the FIRE method\n"
"     CONDITION:\n"
"       MASTER_KEY: method\n"
"       WHEN:\n"
"       - FIRE\n"
"     RANGE: [0, 1e4]\n"
"     default: 0.75\n"
"   dtmax:\n"
"     COMMENT: maximal time step for the FIRE method\n"
"     CONDITION:\n"
"       MASTER_KEY: method\n"
"       WHEN:\n"
"       - FIRE\n"
"     RANGE: [0, 1e4]\n"
"     default: 1.5\n"
"   ionmov:\n"
"     COMMENT: movement ion method\n"
"     CONDITION:\n"
"       MASTER_KEY: method\n"
"       WHEN:\n"
"       - AB6MD\n"
"     EXCLUSIVE:\n"
"       6: simple velocity-Verlet molecular dynamic\n"
"       7: quenched molecular dynamic\n"
"       8: Nose-Hoover thermostat\n"
"       9: Langevin dynamic\n"
"       12: Isokinetic ensemble molecular dynamics\n"
"       13: Iosthermal/isenthalpic ensemble\n"
"     default: 6\n"
"   dtion:\n"
"     COMMENT: time step - Atomic Units (20.670689 AU=0.5 fs)\n"
"     CONDITION:\n"
"       MASTER_KEY: method\n"
"       WHEN:\n"
"       - AB6MD\n"
"     RANGE: [0, 1e3]\n"
"     default: 20.670689\n"
"   mditemp:\n"
"     COMMENT: temperature of molecular dynamics\n"
"     CONDITION:\n"
"       MASTER_KEY: ionmov\n"
"       WHEN: [8, 9, 12, 13]\n"
"#       - 6\n"
"     RANGE: [0, 1e9]\n"
"     default: 300.\n"
"   mdftemp:\n"
"     COMMENT: final temperature of molecular dynamics\n"
"     CONDITION:\n"
"       MASTER_KEY: ionmov\n"
"       WHEN: [8, 9, 12, 13]\n"
"     RANGE: [0, 1e9]\n"
"     default: 300.\n"
"   noseinert:\n"
"     COMMENT: thermostat inertia coefficient for Nose_Hoover dynamics\n"
"     CONDITION:\n"
"       MASTER_KEY: ionmov\n"
"       WHEN:\n"
"       - 8\n"
"     RANGE: [0, 1e9]\n"
"     default: 1e5\n"
"   friction:\n"
"     COMMENT: Friction coefficient for Langevin dynamics\n"
"     CONDITION:\n"
"       MASTER_KEY: ionmov\n"
"       WHEN:\n"
"       - 9\n"
"     RANGE: [0, 1e5]\n"
"     default: 1e-3\n"
"   mdwall:\n"
"     COMMENT: Distance in bohr where atoms can bounce for Langevin dynamics\n"
"     CONDITION:\n"
"       MASTER_KEY: ionmov\n"
"       WHEN:\n"
"       - 9\n"
"     RANGE: [0, 1e5]\n"
"     default: 1e4\n"
"   qmass:\n"
"     COMMENT: Mass of each thermostat (isothermal/isenthalpic ensemble)\n"
"     CONDITION:\n"
"       MASTER_KEY: ionmov\n"
"       WHEN:\n"
"       - 13\n"
"     RANGE: [0, 1e9]\n"
"     default:\n"
"     - 0.\n"
"   bmass:\n"
"     COMMENT: Barostat masses (isothermal/isenthalpic ensemble)\n"
"     CONDITION:\n"
"       MASTER_KEY: ionmov\n"
"       WHEN:\n"
"       - 13\n"
"     RANGE: [0, 1e9]\n"
"     default: 10.\n"
"   vmass:\n"
"     COMMENT: Barostat masses (isothermal/isenthalpic ensemble)\n"
"     CONDITION:\n"
"       MASTER_KEY: ionmov\n"
"       WHEN:\n"
"       - 13\n"
"     RANGE: [0, 1e9]\n"
"     default: 1.\n"
" mix:\n"
"   iscf:\n"
"     COMMENT: mixing parameters\n"
"     EXCLUSIVE:\n"
"       -1: reserved, do not use it.\n"
"       0: direct minimization\n"
"       1: get the largest eigenvalue of the SCF cycle\n"
"       2: simple mixing of the potential\n"
"       3: Anderson mixing of the potential\n"
"       4: Anderson mixing of the potential based on the two previous iterations\n"
"       5: CG based on the minim. of the energy with respect to the potential\n"
"       7: Pulay mixing of the potential based on npulayit previous iterations\n"
"       12: simple mixing of the density\n"
"       13: Anderson mixing of the density\n"
"       14: Anderson mixing of the density based on the two previous iterations\n"
"       15: CG based on the minim. of the energy with respect to the density\n"
"       17: Pulay mixing of the density\n"
"     default: 0\n"
"   itrpmax:\n"
"     COMMENT: maximum number of diagonalisation iterations\n"
"     RANGE: [0, 10000]\n"
"     default: 1\n"
"   rpnrm_cv:\n"
"     COMMENT: stop criterion on the residue of potential or density\n"
"     RANGE: [0., 10.]\n"
"     default: 1e-4\n"
"   norbsempty:\n"
"     COMMENT: No. of additional bands\n"
"     RANGE: [0, 10000]\n"
"     default: 0\n"
"   Tel:\n"
"     COMMENT: electronic temperature\n"
"     RANGE: [0., 1e6]\n"
"     default: 0.\n"
"   occopt:\n"
"     COMMENT: smearing method\n"
"     EXCLUSIVE:\n"
"       1: error function smearing\n"
"       2: normal Fermi distribution\n"
"       3: Marzari cold smearing a=-.5634 (bumb minimization)\n"
"       4: Marzari cold smearing with a=-.8165 (monotonic tail)\n"
"       5: Methfessel and Paxton (same as cold with a=0)\n"
"     default: 1\n"
"   alphamix:\n"
"     COMMENT: Multiplying factors for the mixing\n"
"     RANGE: [0, 1.]\n"
"     default: 0.\n"
"   alphadiis:\n"
"     COMMENT: Multiplying factors for the electronic DIIS\n"
"     RANGE: [0., 10.]\n"
"     default: 2.\n"
" sic:\n"
"   sic_approach:\n"
"     COMMENT: SIC method\n"
"     EXCLUSIVE:\n"
"       none: no self-interaction correction\n"
"       PZ: Perdew-Zunger SIC scheme\n"
"       NK: Non-Koopmans correction (Experimental)\n"
"     default: none\n"
"   sic_alpha:\n"
"     COMMENT: SIC downscaling parameter\n"
"     RANGE: [0, 1.]\n"
"     default: 0.\n"
"   sic_fref:\n"
"     COMMENT: reference occupation fref (for NK case only)\n"
"     CONDITION:\n"
"       MASTER_KEY: sic_approach\n"
"       WHEN:\n"
"       - NK\n"
"     RANGE: [0., 1.]\n"
"     default: 0.\n"
" tddft:\n"
"   tddft_approach:\n"
"     COMMENT: TDDFT method\n"
"     EXCLUSIVE:\n"
"       none: no tddft post-processing\n"
"       TDA: ???\n"
"     default: none\n"
" perf:\n"
"   debug:\n"
"     COMMENT: debug option\n"
"     default: No\n"
"   fftcache:\n"
"     COMMENT: cache size for the FFT\n"
"     default: 8192\n"
"   accel:\n"
"     COMMENT: acceleration\n"
"     EXCLUSIVE:\n"
"       no: no material acceleration\n"
"       CUDAGPU: CUDA\n"
"       OCLGPU: OpenCL on GPU\n"
"       OCLCPU: OpenCL on CPU\n"
"       OCLACC: ???\n"
"     default: No\n"
"   ocl_platform:\n"
"     COMMENT: Chosen OCL platform\n"
"     default: ~\n"
"   ocl_devices:\n"
"     COMMENT: Chosen OCL devices\n"
"     default: ~\n"
"   blas:\n"
"     COMMENT: CUBLAS acceleration\n"
"     default: No\n"
"   projrad:\n"
"     COMMENT: Radius of the projector as a function of the maxrad\n"
"     RANGE: [0., 100.]\n"
"     default: 15.\n"
"   exctxpar:\n"
"     COMMENT: Exact exchange parallelisation scheme\n"
"     EXCLUSIVE:\n"
"       BC: ???\n"
"       OP2P: ???\n"
"     default: OP2P\n"
"   ig_diag:\n"
"     COMMENT: Input guess (T=Direct, F=Iterative) diag. of Ham.\n"
"     default: Yes\n"
"   ig_norbp:\n"
"     COMMENT: Input guess Orbitals per process for iterative diag.\n"
"     RANGE: [1, 1000]\n"
"     default: 5\n"
"   ig_blocks:\n"
"     COMMENT: Input guess Block sizes for orthonormalisation\n"
"     RANGE: [1, 100000]\n"
"     default: [300, 800]\n"
"   ig_tol:\n"
"     COMMENT: Input guess Tolerance criterion\n"
"     RANGE: [0., 1.]\n"
"     default: 1e-4\n"
"   methortho:\n"
"     COMMENT: Orthogonalisation\n"
"     EXCLUSIVE:\n"
"       0: Cholesky\n"
"       1: GS/Chol\n"
"       2: Loewdin\n"
"     default: 0\n"
"   rho_commun:\n"
"     COMMENT: Density communication scheme (DBL, RSC, MIX)\n"
"     default: DEF\n"
"   psolver_groupsize:\n"
"     COMMENT: Size of Poisson Solver taskgroups (0=nproc)\n"
"     RANGE: [0, 1000000]\n"
"     default: 0\n"
"   psolver_accel:\n"
"     COMMENT: Acceleration of the Poisson Solver (0=none, 1=CUDA)\n"
"     EXCLUSIVE:\n"
"       0: none\n"
"       1: CUDA\n"
"     default: 0\n"
"   unblock_comms:\n"
"     COMMENT: Overlap Communications of fields (OFF,DEN,POT)\n"
"     EXCLUSIVE:\n"
"       OFF: synchronous run\n"
"       DEN: ???\n"
"       POT: ???\n"
"     default: OFF\n"
"   linear:\n"
"     COMMENT: Linear Input Guess approach\n"
"     EXCLUSIVE:\n"
"       OFF: ???\n"
"       LIG: ???\n"
"       FUL: ???\n"
"       TMO: ???\n"
"     default: OFF\n"
"   tolsym:\n"
"     COMMENT: Tolerance for symmetry detection\n"
"     RANGE: [0., 1.]\n"
"     default: 1e-8\n"
"   signaling:\n"
"     COMMENT: Expose calculation results on Network\n"
"     default: No\n"
"   signaltimeout:\n"
"     COMMENT: Time out on startup for signal connection (in seconds)\n"
"     RANGE: [-1, 3600]\n"
"     default: 0\n"
"   domain:\n"
"     COMMENT: Domain to add to the hostname to find the IP\n"
"     default: ~\n"
"   inguess_geopt:\n"
"     COMMENT: input guess to be used during the optimization\n"
"     EXCLUSIVE:\n"
"       0: wavelet input guess\n"
"       1: real space input guess\n"
"     default: 0\n"
"   store_index:\n"
"     COMMENT: store indices or recalculate them for linear scaling\n"
"     default: Yes\n"
"   verbosity:\n"
"     COMMENT: verbosity of the output\n"
"     EXCLUSIVE:\n"
"       0: ???\n"
"       1: ???\n"
"       2: ???\n"
"       3: ???\n"
"     default: 2\n"
"   outdir:\n"
"     COMMENT: Writing directory\n"
"     default: .\n"
"   psp_onfly:\n"
"     COMMENT: Calculate pseudopotential projectors on the fly\n"
"     default: Yes\n"
"   pdsyev_blocksize:\n"
"     COMMENT: SCALAPACK linear scaling blocksize\n"
"     default: -8\n"
"   pdgemm_blocksize:\n"
"     COMMENT: SCALAPACK linear scaling blocksize\n"
"     default: -8\n"
"   maxproc_pdsyev:\n"
"     COMMENT: SCALAPACK linear scaling max num procs\n"
"     default: 4\n"
"   maxproc_pdgemm:\n"
"     COMMENT: SCALAPACK linear scaling max num procs\n"
"     default: 4\n"
"   ef_interpol_det:\n"
"     COMMENT: FOE max determinant of cubic interpolation matrix\n"
"     RANGE: [0., 1.]\n"
"     default: 1e-20\n"
"   ef_interpol_chargediff:\n"
"     COMMENT: FOE max charge difference for interpolation\n"
"     RANGE: [0., 1000.]\n"
"     default: 10.\n"
"   mixing_after_inputguess:\n"
"     COMMENT: mixing step after linear input guess (T/F)\n"
"     default: Yes\n"
"   iterative_orthogonalization:\n"
"     COMMENT: iterative_orthogonalization for input guess orbitals\n"
"     default: No\n"
"   check_sumrho:\n"
"     COMMENT: enables linear sumrho check\n"
"     default: 2\n"
"     EXCLUSIVE:\n"
"       0: no check\n"
"       1: light check\n"
"       2: full check\n"
"   experimental_mode:\n"
"     COMMENT: activate the experimental mode in linear scaling\n"
"     default: No\n"
"   write_orbitals:\n"
"     COMMENT: linear scaling write KS orbitals for cubic restart (might take lot of disk space!)\n"
"     default: No\n"
"\n"
