#
# Config file generated by Abinit
#
# NOTE: You may adjust it before running 'configure'.
#

# Abinit paths
with_abinit_builddir="/gpfs/home/chuang3/XCEP_codes/abinit-7.10.4_xcep_v1pbc"
with_abinit_srcdir="/gpfs/home/chuang3/XCEP_codes/abinit-7.10.4_xcep_v1pbc"

# C support
CPP="gcc -E"
CPPFLAGS=""
CC="gcc"
CFLAGS=" -g -O2 -mtune=native -march=native  "
CC_LDFLAGS="    "

# C++ support
XPP=""
XPPFLAGS="    "
CXX="g++"
CXXFLAGS=" -g -O2 -mtune=native -march=native  "
CXX_LDFLAGS="    "

# Fortran support
FPP=""
FPPFLAGS="    "
FC="gfortran"
FCFLAGS=" -g -ffree-line-length-none   -O2 -mtune=native -march=native"
FC_LDFLAGS="    "
with_fc_vendor="gnu"
with_fc_version="4.8"

# Python support
PYTHON="python"
PYFLAGS=""
PYTHON_CPPFLAGS="-I/usr/include/python2.7 -I/usr/lib64/python2.7/site-packages/numpy/core/include"

# Utilities
AR="ar"
ARFLAGS="     rc"
RANLIB="ranlib"

# Parallel I/O use flags
lib_etsf_io_incs=""
lib_etsf_io_libs=""
lib_netcdf_incs=""
lib_netcdf_libs=""

# Linear algebra use flags
lib_linalg_fcflags=""
lib_linalg_ldflags=""
lib_linalg_incs=""
lib_linalg_libs="-llapack  -lblas  "

# FFT use flags
lib_fft_incs=""
lib_fft_libs=""

# Feature triggers use flags
lib_bigdft_incs="-I$(fallbacks_instdir)/include"
lib_bigdft_libs="-L$(fallbacks_instdir)/lib -lbigdft-1 -labinit -lyaml"
lib_fox_incs=""
lib_fox_libs=""
lib_gsl_incs="@lib_gsl_incs@"
lib_gsl_libs="@lib_gsl_libs@"
lib_levmar_incs="@lib_levmar_incs@"
lib_levmar_libs="@lib_levmar_libs@"
lib_libpspio_incs=""
lib_libpspio_libs=""
lib_libxc_incs="-I$(fallbacks_instdir)/include"
lib_libxc_libs="-L$(fallbacks_instdir)/lib -lxc"
lib_papi_incs="@lib_papi_incs@"
lib_papi_libs="@lib_papi_libs@"
lib_wannier90_bins=""
lib_wannier90_incs=""
lib_wannier90_libs=""
lib_yaml_incs=""
lib_yaml_libs=""
