subroutine welcome_message(file_dfet_out)

 integer :: file_dfet_out 

 character(len=100) :: str 

 call get_time_date(str)
  
 write(file_dfet_out,'(a,a)')'program started on ',trim(str)
 write(file_dfet_out,'(a)')''
 write(file_dfet_out,'(a)')''
 write(file_dfet_out,*) '         _____                       _   '
 write(file_dfet_out,*) '        |  __ \                     | |  '
 write(file_dfet_out,*) '        | |__) |__  __ _ _ __  _   _| |_ '
 write(file_dfet_out,*) "        |  ___/ _ \/ _` | '_ \| | | | __|"
 write(file_dfet_out,*) '        | |  |  __/ (_| | | | | |_| | |_ '
 write(file_dfet_out,*) '        |_|   \___|\__,_|_| |_|\__,_|\__'
 write(file_dfet_out,'(a)')''
 write(file_dfet_out,'(a)')''
 write(file_dfet_out,'(a)')'    Peanut: A Kohn-Sham density functional theory simulation based on'
 write(file_dfet_out,'(a)')'          embedded cluster density approximation (v5.2 PBC)'
 write(file_dfet_out,'(a)')''
 write(file_dfet_out,'(a)')'                           Chen Huang         '
 write(file_dfet_out,'(a)')'  '
 write(file_dfet_out,'(a)')'                Department of Scientific Computing'
 write(file_dfet_out,'(a)')'          Florida State University, Tallahassee, FL 32306 '
 write(file_dfet_out,'(a)')'   '
 write(file_dfet_out,'(a)')'                Copyright (c) 2015-2020 Chen Huang'
 write(file_dfet_out,'(a)')'  '
 write(file_dfet_out,'(a)')' This program is free software: You can redistribute it and/or modify '
 write(file_dfet_out,'(a)')' it under the terms of the gnu general public license as published by  '
 write(file_dfet_out,'(a)')' the free software foundation, either version 3 of the license, or '
 write(file_dfet_out,'(a)')' (at your option) any later version.'
 write(file_dfet_out,'(a)')'  '
 write(file_dfet_out,'(a)')'  '
 write(file_dfet_out,'(a)')' Revisions:'
 write(file_dfet_out,'(a)')' =========='
 write(file_dfet_out,'(a)')'  - Removed system() functions which are not multi-thread safe'
 write(file_dfet_out,'(a)')'  - Becke function is only nested once to make atom weight soft'
 write(file_dfet_out,'(a)')'  - ABINIT only outputs dExc/dvks '
 write(file_dfet_out,'(a)')'  - Start removing XCPP codes and KLI '
 write(file_dfet_out,'(a)')'  - Modulized the codes by making new subroutines: solve_z(), solve_total_vxc(), dfet() '
 write(file_dfet_out,'(a)')'  - Vaccum level is defined as Fermi + barrier '
 write(file_dfet_out,'(a)')'  - Orbital shift is now solved in ABINIT in recip. space using chen_orb_shift_recip_NEW() '
 write(file_dfet_out,'(a)')'  - Density perturbation is solved in recip space using chen_dfpt_sternheimer_frac_recip() '
 write(file_dfet_out,'(a)')'  - Regularization in solve_z() and solve_total_xc() is done with grad(x) (12/20/2017)'
 write(file_dfet_out,'(a)')'  - chen_dfpt_sternheimer_frac_recip() works directly on wfn in planewave basis. (12/22/2017)'
 write(file_dfet_out,'(a)')'  - chen_orb_shift_recip_NEW() works directly on wfn in planewave basis. (12/22/2017)'
 write(file_dfet_out,'(a)')'  - chen_dfpt_sternheimer_frac_recip() only considers orbitals with occ > 1e-6. (12/22/2017)'
 write(file_dfet_out,'(a)')'  - Add mpi_barrier() before mpi_allreduced() to avoid running out memory (12/23/2017)'
 write(file_dfet_out,'(a)')'  - Harris functional is added (12/24/2017)'
 write(file_dfet_out,'(a)')'  - New keywords reg_z and reg_vxc (12/30/2017)'
 write(file_dfet_out,'(a)')'  - New dfet_PDEopt() for directly minimizing density difference w/ Coulomb metric.(1/3/2018)'
 write(file_dfet_out,'(a)')'  - The status of the processes of XCEP is monitored by log_cluster_*.txt files.(1/3/2018)'
 write(file_dfet_out,'(a)')'  - New calc_delta_fermi() for computing Ef change w/ cluster and env coupled. (1/6/2018)'
 write(file_dfet_out,'(a)')'  - dfet_PDEopt() can now treat charge transfer between cluster and env. (1/6/2018)'
 write(file_dfet_out,'(a)')'  - Electron numbers in cluster and env are determined by Becke method (1/11/2018)'
 write(file_dfet_out,'(a)')'  - pulay mixing of vks now with a metric. (1/12/2018) '
 write(file_dfet_out,'(a)')'  - var dtset%calc_mode is added in src/44_abitypes_defs/defs_abitypes.F90 (1/18/2018) '
 write(file_dfet_out,'(a)')'  - var dtset%conv_unocc_orb is added to converge virtual orbitals in vtowfk() (1/18/2018) '
 write(file_dfet_out,'(a)')'  - XCEP and ABINIT now can do non-spin-polarized calculations. (1/24/2018)'
 write(file_dfet_out,'(a)')'  - EXX on each atom is now outputed in xcep.out file. (1/26/2018)'
 write(file_dfet_out,'(a)')'  - dfet_zp() is now working and is the default, (1/31/2018)'
 write(file_dfet_out,'(a)')'  - dfet_zp() is now based on screened Coulumb potential, (1/31/2018)'
 write(file_dfet_out,'(a)')'  - dfet_zp() is now using GR-Pulay, (2/1/2018)'
 write(file_dfet_out,'(a)')'  - dipole moment is added. (2/9/2018)'
 write(file_dfet_out,'(a)')'  - fixed a sever bug related to atom weights. (3/25/2018)'
 write(file_dfet_out,'(a)')'  - dfet_vh() is added (however, disabled) (3/25/2018)'
 write(file_dfet_out,'(a)')'  - environment can have zero atom. (7/19/2018)'
 write(file_dfet_out,'(a)')'  - global_fermi>0 is enforced. (7/20/2018)'
 write(file_dfet_out,'(a)')'  - augmented lagrange method is added (u_base is updated every iter.). (7/28/2018)'
 write(file_dfet_out,'(a)')'  - a severe bug (too small range in screened hartree) in ZP method is fixed. (7/28/2018)'
 write(file_dfet_out,'(a)')'  - density mixing is added for DFET (8/1/2018)'
 write(file_dfet_out,'(a)')'  - do_aug_lag keyword is added to switch on/off aug-lag method (8/9/2018)'
 write(file_dfet_out,'(a)')'  - global_vks is mixed at the first iteration (8/21/2018)'
 write(file_dfet_out,'(a)')'  - charges in cluster and env are distributed by having common fermi level. (10/4/2018)'
 write(file_dfet_out,'(a)')'  - plateau and local fermi levels are used to partition system`s KS potentials. (10/21/2019)'
 write(file_dfet_out,'(a)')'  - potential for local fermi level is implemented. (11/1/2019)'
 write(file_dfet_out,'(a)')'  - local fermi codes are removed. (1/3/2019)'
 write(file_dfet_out,'(a)')'  - start to restore global fermi code. (1/3/2019)'
 write(file_dfet_out,'(a)')'  - forces are added. (1/10/2019)'
 write(file_dfet_out,'(a)')'  - bugs in force_xc1 are finally fixed. (1/11/2019)'
 write(file_dfet_out,'(a)')'  - ECDA and abinit are modified to relax geometry. (1/11/2019)'
 write(file_dfet_out,'(a)')'  - For geometry relax, global system works with ionmov=2. (1/15/2019)'
 write(file_dfet_out,'(a)')'  - For geometry relax, clusters and envs re-run scfcv(), when xred are updated). (1/15/2019)'
 write(file_dfet_out,'(a)')'  - patch_xc.F90 has been created. (1/16/2019)'
 write(file_dfet_out,'(a)')'  - dfet_zp is modified to make ECDA fully variational even with regularization. (1/23/2019)'
 write(file_dfet_out,'(a)')'  - L-BFGS due to Nocedal and Zhu is added to direct minimize ECDA. (1/24/2019)'
 write(file_dfet_out,'(a)')'  - solve_z now considers zp_coeff to make ECDA fully variational. (1/27/2019)'
 write(file_dfet_out,'(a)')'  - dAtomW_dR and dClusterW_dR are shared among processors for force calc. (1/28/2019)'
 write(file_dfet_out,'(a)')'  - Restore Coulomb penalty in ZP method, which adds a laplacian in solve_z(). (1/28/2019)'
 write(file_dfet_out,'(a)')'  - new definition for vks_clu: vks_clu = w_clu*(vks-ferm-vac). Similar for vks_env (2/4/2018)'
 write(file_dfet_out,'(a)')'  - Total OEP is solved using penalty function: lambda*<vks-vh-vpsp,vks-vh-vpsp> (2/10/2018)'
 write(file_dfet_out,'(a)')'  - The regularization in solve_z() is now completed based on Zhao-Parr method. (2/21/2019)'
 write(file_dfet_out,'(a)')'  - non-HF force due to regularization term is added. (2/24/2019)'
 write(file_dfet_out,'(a)')'  - My L-BFGS solver is added to optimize geometry. (2/28/2019)'
 write(file_dfet_out,'(a)')'  - solve_total_oep_reg.f90 bug fixed (new definition for OEP equation). (3/2/2019)'
 write(file_dfet_out,'(a)')'  - vks is mixed at iscf=1. Initial vks is shifted such that avg(vks)=avg(vpsp). (3/3/2019)'
 write(file_dfet_out,'(a)')'  - first-order xc correction is added. (4/15/2019)'
 write(file_dfet_out,'(a)')'  - cluster`s XC energy density is corrected by LDA. (5/15/2019)'
 write(file_dfet_out,'(a)')'  - Many routines (OF_cgmin_tot, OF_dfpt, OF_dfpt_inv, OF_drho_dN) are added. (12/31/2019)'
 write(file_dfet_out,'(a)')'  - Env can now be treated by OF-DFT. (12/31/2019)'
 write(file_dfet_out,'(a)')'  - solve_z() is now preconditioned. (1/2/2020)'
 write(file_dfet_out,'(a)')'  - For dipole calculation, zion is now read from global_system/zion.dat. (1/10/2020)'
 write(file_dfet_out,'(a)')'  - Mix uemb and vks together. (1/10/2020)'
 write(file_dfet_out,'(a)')'  - total OEP equation is solved by transforming variable to avoid laplacian. (1/20/2020)'
 write(file_dfet_out,'(a)')'  - Initial guess for global_vxc is computed as vks-vpsp-vhart. (1/23/2020)'
 write(file_dfet_out,'(a)')'  - Linear mixing is used to damp u and zvec. (1/23/2020)'
 write(file_dfet_out,'(a)')'  - dE/dvs is enforsed to zero before calling solve_total_vxc(). (1/27/2020)'
 write(file_dfet_out,'(a)')'  - density mixing is added to dfet_zp(). More accurate results (seems) (2/17/2020)'
 write(file_dfet_out,'(a)')'  - In solve_z(), A*x is explicitely calculated to avoid error accumulation. (2/17/2020)'
 write(file_dfet_out,'(a)')'  - L-BFGS based on z-solver is added. solve_z_lbfgs_exlsr(). (2/17/2020)'
 write(file_dfet_out,'(a)')'  - Bug in OF_cgmin_tot() is fixed, now the code is based on minimizing <phi,A,phi>/<phi,phi> (4/2020)'
 write(file_dfet_out,'(a)')'  - PBE0 is correctly added to both global and ECDA cases. (4/2020)'




 write(file_dfet_out,'(a)')''
 write(file_dfet_out,'(a)')''
 write(file_dfet_out,'(a)')''




end subroutine  welcome_message
